# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(CONFIG_ARCH_WAIPIO), y)
include $(TOUCH_ROOT)/config/waipio_touch.conf
LINUXINCLUDE += -include $(TOUCH_ROOT)/config/waipio_touch.h
#                   -I$(TOUCH_ROOT)/driver/platform/waipio/inc
endif

#obj-$(CONFIG_TOUCHSCREEN_XIAOMI_TOUCHFEATURE)   += xiaomi/
#obj-$(CONFIG_TOUCHSCREEN_ST_FTS_V521_SPI)       += fts_spi/
obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_9916)       += goodix_9916/

#obj-m += xiaomi_touch.o

obj-$(CONFIG_TOUCHSCREEN_XIAOMI_TOUCHFEATURE) += xiaomi/xiaomi_touch.o
